# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en-US"

title: Her Animals

title_separator: "|"
name: "Astoria Ho"
repository: "astoriah/her_animals"

email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: "/her-animals" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: her_animals
github_username:  her_animals

# Site settings
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-paginate

timezone: America/Los_Angeles

include: ["_pages"]

#paginate: 10

author: 
  name: "Astoria"
  avatar: /images/memoji.png 
  bio: "My hobby farming journey in the Pacific Northwest!"
  # location: "Washington"
  links:
    - label: "@Her_Animals"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/her_animals"

atom_feed: 
  path: 
  hide: true 

#site footer
footer:
  links:
    - label: "@her_animals"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/her_animals"

#collections 
collections: 
  flora: 
    output: true
    permalink: /:collection/:path 
  flavor: 
    output: true
    permalink: /:collection/:path 

#defaults 
defaults: 
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  #_posts
  - scope: 
      path: "/:slugified_categories/:year/:month/:day/:title"
      type: posts
    values: 
      layout: single
      show_date: true
      author_profile: true
   # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true


#google_site_verification: "yourverificationcode"
#https://support.google.com/analytics/answer/1142414?hl=en

# analytics:
#   provider: "google-gtag"
#   google:
#     tracking_id: "UA-1234567-8"
#     anonymize_ip: false # default


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/